spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cqcq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: KdCDFG53G6MGSGSk
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}

server:
  port: 8080
  servlet:
    context-path: /cqcq

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oeong.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL

logging:
  level:
    root: info
    com.oeong: debug
